server:
  port: 8112
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhang
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.zhang.mapper: debug
#home:安装地址
jodconverter:
  local:
    office-home: C:/Program Files (x86)/OpenOffice 4
    max-tasks-per-process: 10
    port-numbers: 8100
    enabled: true