server:
  port: 8099
spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/zhang?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
logging:
  level:
    com.zhang.mapper: debug
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

