server:
  port: 8089
spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/zhang?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
logging:
  level:
    com.code.gen.out.mapper: debug
mybatis-plus:
  mapper-locations: classpath:/com.code.gen.out.mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.code.gen.out.entity
#  typeEnumsPackage: com.code.gen.out.entity
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: assign_id
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: ignored
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: Y
      logic-not-delete-value: N
      db-type: mysql
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
